export const SUMMARY_LOADED = 'SUMMARY_LOADED';
export const IS_ABSOLUTE_CHANGED = 'IS_ABSOLUTE_CHANGED';
export const IS_ALL_PERIOD_CHANGED = 'IS_ALL_PERIOD_CHANGED';
export const IS_ASCENDING_CHANGED = 'IS_ASCENDING_CHANGED';
export const POPULATION_LOADED = 'POPULATION_LOADED';